### ISSUE TITLE
RailgunsRetargetMini: Disable EM Railguns when the sphere is complete

### ISSUE THREAD

**Issue by LordMike** [starfi5h/DSP_Mod#11]
It'd be cool to have an option on `RailgunsRetargetMini` that disables the rail gun if the Dyson Sphere is complete and the new solar sail would go in the Dyson Swarm.

I'm playing to complete my spheres, and have to keep watching that none of my starts are receiving swarms.

Bonus: Limit the railguns if they are sending out more solar sails than the sphere can currently absorb. :)

**Comment by starfi5h** [comment]
They are featured in another mod [SmartEjectors](https://dsp.thunderstore.io/package/DanielHeEGG/SmartEjectors/).

**Comment by LordMike** [comment]
Tried it out - and while it seems to work, it's quite slow. Will report it to them.
