### ISSUE TITLE
[AlterTickrate] ray receivers broken

### ISSUE THREAD

**Issue by andrewtranter** [starfi5h/DSP_Mod#14]
This mod affects ray receivers
they produce virtually no critical photons, perhaps 1/20th
eventually after a long time your supply of antimatter dries up and you have to do a black start of your WHOLE empire

i've several mods installed, so potentially related. however uninstalling this plugin meant everything began working correctly again.

**Comment by andrewtranter** [comment]
ah, apologies, yes AfterTickrate.
I haven't tried SampleAndHoldSim yet.

**Comment by andrewtranter** [comment]
You were correct. Doh I should have realized!
Took me 20minutes to empty all the belts and stacking critical photons, but I made a save to easily test.
Narrowed it down to More Megastructures addon causing it. I suppose that makes sense with different types of stuff they do.
This planet has 15.7k photos/minute vanilla, 15.7k/min w More Megastructures (and many other mods), 15.6k/min with just AlterTickrate, 510 photons/min with AlterTickrate & More Megastructures.

I guess its up to you weather you want to try to make it compatible.

AlterTickrate helped my fps by about 5-7fps. Seems my bottleneck is elsewhere. Building 5 or 6 spheres concurrently, with 40k floating components being absorbed each, must be pushing it a bit.

**Comment by starfi5h** [comment]
For mods that add new recipes (e.g. MoreMegaStructure, GenesisBook, BetterMachines), I suggest using SampleAndHoldSim instead. By changing recipes, they already trigger prototype abnormality, so the downside of SampleAndHoldSim is negligible.
![abnormal](https://user-images.githubusercontent.com/50672801/229271734-454d5316-7697-4a7c-8a59-a9dcb649edd3.jpg)
Some mods hide the "Incorrect data" pop-up, and some mods (GalacticScale, AchievementsEnabler) disable the local abnormality checking.

AlterTickrate is more for vanilla players who wish to upload to leaderboard (Milkyway). It has lower risk of triggering data abnormal.

**Comment by andrewtranter** [comment]
No probs. The experimental note for SampleAndHoldSim had me thinking it wasnt ready.
So far SampleAndHoldSim works and seems to improve performance better than AlterTickrate.
