### ISSUE TITLE
[SampleAndHoldSim]當以傳送帶以外的物流方式消耗(增加)貨物時UIStationStoragePeriod不會正常工作

### ISSUE THREAD

**Issue by blacksnownight** [starfi5h/DSP_Mod#15]
就不寫版本號了，因在0.4.2版本第一次使用時就有注意到
說真的到底算不算bug，其實我也不太知道
其實只要有能物流系統的都會有這個 問題(大塔小塔大礦機)
![QQ图片20230405040719](https://user-images.githubusercontent.com/128919146/229908337-5be9ba89-7974-4ec4-968e-7b62f1ad3c2e.png)
比如說拉了9條傳送帶的大礦機，因有物理(傳送帶)所UIStationStoragePeriod會顯示流速
但當被小飛機瘋狂壓榨的大礦機，因沒有傳送帶所UIStationStoragePeriod永遠都是0
![QQ图片20230405040856](https://user-images.githubusercontent.com/128919146/229908920-057970a5-239a-4837-b47e-ddb784421ad5.png)
同理的還有大塔跟小塔，因是使用運輸船跟小飛機，大塔就全是0
![QQ图片20230405041152](https://user-images.githubusercontent.com/128919146/229909354-f0dbe0f5-08e4-4ae7-bb13-8d3982aa05fc.png)
小塔是原料只會顯示消耗，成品能正常顯示增加(但當被大塔取走成品時，是不會有任何反應的)
![QQ图片20230405041450](https://user-images.githubusercontent.com/128919146/229910010-0cd8f54f-5592-4d7f-a86f-8b4f8343addc.png)

**Comment by starfi5h** [comment]
mod說明文檔中可能寫得不太好
`UIStationStoragePeriod`其實專指是物流塔的"傳送帶"輸入/輸出速率
因為要倍增/縮減產物需要記錄"儲存貨物數量在不是小飛機/飛船造成的變化"
我想說這個數據可能會有使用者感興趣, 就額外做了個UI顯示出來, 當作mod的附帶功能

其實我不太清楚使用者真正想要看到的數據是什麼 - 貨物數量的總變化率? 小飛機的流通量? 帶子的流通量?
還是都要, 分開顯示?

**Comment by blacksnownight** [comment]
鍋昨天刪多了，忙到現在
以我的想法的話，因物流塔本身就有在途的設定(+200-200+2000-2000)
所以是否可能就是當有使用到傳送帶才會顯示這個值
如沒傳送帶就不顯示這個值?

**Comment by starfi5h** [comment]
0.5.2版更新: 流速為0時不顯示
