### ISSUE TITLE
[SampleAndHoldSim] 疑問，奇怪的負值

### ISSUE THREAD

**Issue by blacksnownight** [starfi5h/DSP_Mod#16]
- Enable station storage to have negative values to prevent generating extra item.
在0.5.0對物流塔增加了負值已防止虛空造物
但現在再重搓球發現一個奇怪的現象
狀況是這樣的
我帆打完了，大塔本地需求‧星際供應
且運輸船起送量拉至1%
![QQ图片20230408081033](https://user-images.githubusercontent.com/128919146/230754142-b0ed00b3-c52d-47ac-bb4c-99a43915c544.png)

打帆小塔設置供應
且運輸機起送量拉至1%
![QQ图片20230408081827](https://user-images.githubusercontent.com/128919146/230754151-de638e54-c0e6-4cfa-81ba-6d5756f99f62.png)
然後我到其他行星也這麼做在回來時(當恆星不只一顆行星時)
小塔卻產生了負值
疑問點在於，並不是生產的東西，且物品也是經過大塔->小塔在小塔->大塔->別的需要太陽帆的地方
沒有虛空造物為甚麼會有負值?
我基本沒有看過大塔有負值，這種情況都是在小塔設置1%起送且大塔回收時發生的。

**Comment by starfi5h** [comment]
負值是由傳送帶流出物流塔造成的, 和生不生產沒有關係
比方說原本倉儲有5個貨物, 用1條藍帶(30/s = 0.5/tick)流出
在正常遊戲時, 工廠內部的1個貨物 = 工廠外部的1個貨物
每2tick從物流塔放到傳送帶上。在10tick過去後, 倉儲=0, 傳送帶上有5個貨物
在倍率開至10時, 工廠內部的1個貨物 = 工廠外部(物流塔)的10個貨物
在第一個tick將1個貨物放到傳送帶上而倉儲因為放大扣10。在10tick過去後, 倉儲=-5, (工廠內部)傳送帶上有1個貨物
不知道這樣解釋有沒有比較清楚

我不知道你的小塔大塔和傳送帶是怎麼配置的, 因此無法復現
如果你能在提供直接在沙盒中貼上就可以復現問題的藍圖, 我可以研究看看

**Comment by blacksnownight** [comment]
大塔單獨無任何傳送帶
小塔就打帆用的赤道上邊的回歸線很簡單的藍圖
[BLUEPRINT0,10,2311,0,0,0,0,0,638160.txt](https://github.com/starfi5h/DSP_Mod/files/11185727/BLUEPRINT0.10.2311.0.0.0.0.0.638160.txt)
倍率為8

**Comment by starfi5h** [comment]
![image](https://user-images.githubusercontent.com/50672801/230801533-2f4b38f1-3323-43d5-933d-ee16dd980dd8.png)
你發的藍圖並沒有什麼異常
不管設置是供給還是需求, 只要有輸出口-傳送帶流出貨物就有可能變成負值, 這就是mod的特性
除非是物流塔在沒有傳送帶輸出口的情況下, 數量仍會有時變成負的, 那才是bug

**Comment by blacksnownight** [comment]
> ![image](https://user-images.githubusercontent.com/50672801/230801533-2f4b38f1-3323-43d5-933d-ee16dd980dd8.png) 你發的藍圖並沒有什麼異常 不管設置是供給還是需求, 只要有輸出口-傳送帶流出貨物就有可能變成負值, 這就是mod的機制 除非是物流塔在沒有傳送帶輸出口的情況下, 數量仍會有時變成負的, 那才是bug

了解，謝謝，辛苦了。

**Comment by blacksnownight** [comment]
了解，謝謝，辛苦了。
