### ISSUE TITLE
[LossyCompression] Version 0.2.3 藍框報錯

### ISSUE THREAD

**Issue by blacksnownight** [starfi5h/DSP_Mod#17]
不知道為甚麼感覺像bug測試員...算了
![QQ图片20230414132144](https://user-images.githubusercontent.com/128919146/231948437-44570d9e-f661-4182-a0c4-bc167f7f8ca0.png)
There was an issue loading data of mod starfi5h.plugin.LossyCompression.
Your save game could be corrupted! Please report this to mod author.

Message: Unable to read beyond the end of the stream., Stacktrace:
  at System.IO.MemoryStream.InternalReadInt32 () [0x00034] in <2fa7a6a452ca43df998f07fd1486c0df>:0 
  at (wrapper remoting-invoke-with-check) System.IO.MemoryStream.InternalReadInt32()
  at System.IO.BinaryReader.ReadInt32 () [0x00015] in <2fa7a6a452ca43df998f07fd1486c0df>:0 
  at LossyCompression.DysonSwarmCompress.Import (System.IO.BinaryReader r) [0x00000] in <156fe393455745bf890acc38d22a30ef>:0 
  at LossyCompression.Plugin.Import (System.IO.BinaryReader r) [0x00034] in <156fe393455745bf890acc38d22a30ef>:0 
  at crecheng.DSPModSave.Patches.LoadData (System.IO.FileStream fileStream) [0x00147] in <c276797304bf4f0484e515702ce6a461>:0 

[logoutput]
[Message:   BepInEx] BepInEx 5.4.21.0 - DSPGAME (2023/1/25 下午 07:44:09)
[Info   :   BepInEx] Running under Unity v2018.4.12.5889476
[Info   :   BepInEx] CLR runtime version: 4.0.30319.17020
[Info   :   BepInEx] Supports SRE: False
[Info   :   BepInEx] System platform: Bits64, Windows
[Message:   BepInEx] Preloader started
[Info   :   BepInEx] Loaded 1 patcher method from [BepInEx.Preloader 5.4.21.0]
[Info   :   BepInEx] Loaded 1 patcher method from [DSPOptimizationsPreloader 1.0.0.0]
[Info   :   BepInEx] 2 patcher plugins loaded
[Info   :   BepInEx] Patching [UnityEngine.CoreModule] with [BepInEx.Chainloader]
[Info   :   BepInEx] Patching [Assembly-CSharp] with [DSPOptimizations.Preloader]
[Info   :DSPOptimizations Preloader] Successfully ran preloader patch
[Message:   BepInEx] Preloader finished
[Message:   BepInEx] Chainloader ready
[Message:   BepInEx] Chainloader started
[Info   :   BepInEx] 6 plugins to load
[Info   :   BepInEx] Loading [Auxilaryfunction 2.0.2]
[Info   :   BepInEx] Loading [DSP Mod Save 1.1.4]
[Info   :   BepInEx] Loading [DSPOptimizations 1.1.14]
[Info   :DSPOptimizations] 8 optimization sets loaded
[Info   :   BepInEx] Loading [CompressSave 1.2.2]
[Info   :   BepInEx] Loading [LossyCompression 0.2.3]
[Info   :LossyCompression] cargoPath:False dysonShell:False dysonSwarm:False
[Info   :LossyCompression] lazyLoad:True reduceRAM:True
[Info   :LossyCompression] DSPOptimizations compatibility - OK
[Info   :   BepInEx] Loading [SampleAndHoldSim 0.5.2]
[Message:   BepInEx] Chainloader startup complete
[Info   :DSPOptimizations] 4 commands loaded from DSPOptimizations
[Info   :DSP Mod Save] DSP Mod Save is initialized!
[Info   :SampleAndHoldSim] ThreadCount: 24
[Info   :DSP Mod Save] _autosave_tmp: Game mod save not exist
[Info   :SampleAndHoldSim] ThreadCount: 24
[Info   :LossyCompression] Import format version: 1
[Info   :LossyCompression] Decompress DysonShell: 0 bytes 2E-06s
[Error  :DSP Mod Save] starfi5h.plugin.LossyCompression :mod data import error!
[Error  :DSP Mod Save] Unable to read beyond the end of the stream.
  at System.IO.MemoryStream.InternalReadInt32 () [0x00034] in <2fa7a6a452ca43df998f07fd1486c0df>:0 
  at (wrapper remoting-invoke-with-check) System.IO.MemoryStream.InternalReadInt32()
  at System.IO.BinaryReader.ReadInt32 () [0x00015] in <2fa7a6a452ca43df998f07fd1486c0df>:0 
  at LossyCompression.DysonSwarmCompress.Import (System.IO.BinaryReader r) [0x00000] in <156fe393455745bf890acc38d22a30ef>:0 
  at LossyCompression.Plugin.Import (System.IO.BinaryReader r) [0x00034] in <156fe393455745bf890acc38d22a30ef>:0 
  at crecheng.DSPModSave.Patches.LoadData (System.IO.FileStream fileStream) [0x00147] in <c276797304bf4f0484e515702ce6a461>:0 
[Warning:LossyCompression] Format version:1 Compress version:

先說設置吧
LazyLoad:ture
ReduceRAM:ture
CargoPath:false
DysonShell:false
DysonSwarm:false

情況是這樣子的，當我打開尚未使用此mod的存檔時，沒有問題
但當我關閉遊戲，然後加載此存檔時，就報錯了

**Comment by starfi5h** [comment]
感謝回報。匯入mod數據時判斷版本號的條件沒有寫好, 導致在讀取沒有壓縮數據時出錯。
已經在0.3.0版本中修復了。

**Comment by blacksnownight** [comment]
已解決
不過似乎跟CompressSave有點不相容(?)
我CompressSave type:lz4 level:0(全都default設定)
我個人的存檔是4.98G lz4壓縮至3.5G 保存時間約12秒
自動保存同樣也是採用lz4壓縮，並不是保存原始遊戲的存檔
但同樣的設置
LazyLoad:ture
ReduceRAM:ture
CargoPath:false
DysonShell:false
DysonSwarm:false
保存時間幾乎跟原始遊戲相同的(大概吧 原始遊戲我個人上去就3幀電競5幀邏輯)
![QQ图片20230415021201](https://user-images.githubusercontent.com/128919146/232124270-6f0b5ed6-d072-4180-b3e3-e472daf8db60.png)
如果已敘述來說，應該是保存原始遊戲的存檔(非壓縮存檔)才會去生成戴森殼數據然後刪掉
壓縮式存檔不應該會有這樣的...動作?
不過這個其實我算是可接受範圍，因大幅減少了內存占用
在使用此mod前我個人存檔開啟需要用到100G的虛擬內存+30G的實體內存
現只需要10G的實體內存+36G的虛擬內存，不用每次開個遊戲關個遊戲都能吃碗方便麵了
還是要說聲謝謝。

**Comment by starfi5h** [comment]
> 如果已敘述來說，應該是保存原始遊戲的存檔(非壓縮存檔)才會去生成戴森殼數據然後刪掉 壓縮式存檔不應該會有這樣的...動作? 

在設置把這個mod可提供的壓縮的選項都設成false, 那壓縮自然就沒有效果啦
只有在DysonShell這個選項打開才會跳過生成戴森殼數據的階段
DysonShell是無損的, 它保存的數據就是在延遲載入前維持球殼運作機制所需的必要數據(藍圖數據+進度), 生成模型也是用原版的方法。也就是使用LazyLoad延遲載入和使用DysonShell壓縮的風險其實是一樣的。

**Comment by blacksnownight** [comment]
> > 如果已敘述來說，應該是保存原始遊戲的存檔(非壓縮存檔)才會去生成戴森殼數據然後刪掉 壓縮式存檔不應該會有這樣的...動作?
> 
> 在設置把這個mod可提供的壓縮的選項都設成false, 那壓縮自然就沒有效果啦 只有在DysonShell這個選項打開才會跳過生成戴森殼數據的階段 DysonShell是無損的, 它保存的數據就是在延遲載入前維持球殼運作機制所需的必要數據(藍圖數據+進度), 生成模型也是用原版的方法。也就是使用LazyLoad延遲載入和使用DysonShell壓縮的風險其實是一樣的。

我不開啟DysonShell的疑問就是，如果我再開啟DysonShell的情況下，保存一個原始存檔
那我開啟原始遊戲時並載入此原始存檔(就是不使用mod)，殼是否會丟失?

**Comment by starfi5h** [comment]
不會丟失。原始存檔就是包含完整信息的存檔, 在不用mod時載入也不會丟失數據。
CompressSave有個原保存按鈕, 這個相當於同等的功能。目的就是讓玩家在遊戲更新前保存原檔避免更新後mod失效。

**Comment by blacksnownight** [comment]
> 不會丟失。原始存檔就是包含完整信息的存檔, 在不用mod時載入也不會丟失數據。 CompressSave有個原保存按鈕, 這個相當於同等的功能。目的就是讓玩家在遊戲更新前保存原檔避免更新後mod失效。

大概懂了，比如說我想保存一個原始存檔 就compress - off後保存

**Comment by starfi5h** [comment]
是的。設置按鈕就是為了方便快速切換壓縮保存和原版保存。
