### ISSUE TITLE
[request]show both per second, and per minute on vein overlay in map view.

### ISSUE THREAD

**Issue by Layarion** [starfi5h/DSP_Mod#18]
I'd like to see both, instead of just one or the other. it would looks something like the image below
![image](https://user-images.githubusercontent.com/7917992/232373934-a83f4779-75a0-4480-ba02-318ed4fd8e7d.png)

**Comment by starfi5h** [comment]
Thanks for the suggestion, the feature is now available in 1.1.0 version.  
To see both unit, edit config file and set both `ShowItemsPerSecond` and `ShowItemsPerMinute` to true.

**Comment by Layarion** [comment]
ty doing that now
