### ISSUE TITLE
射线锅吃透镜的速度异常快

### ISSUE THREAD

**Issue by Terrevil** [starfi5h/DSP_Mod#19]
问题复现条件
ratio=10
装时间加速3x 或 4x ：https://dsp.thunderstore.io/package/dsp-mods/DspGameSpeed/
半球2500口锅都在吃透镜

用你的mod前是1位数/秒
用你的mod后是3位数/秒

锅消耗透镜的速度没有明显变化
可能是传送带+大量分流器的物流系统问题。
送透镜的主动脉是绿带，旁支是蓝带，所以每个分流器基本上都是1绿输入，1绿+2蓝出

**Comment by starfi5h** [comment]
我无法复现问题。
只有这2个mod吗? 在Ratio调整至1或勾选Focus local问题还会存在吗?
方便的话可以提供2500锅的蓝图吗?

**Comment by Terrevil** [comment]
[DSM 0.3a Ray Receivers x 784 [Polar] with [Lens Input].txt](https://github.com/starfi5h/DSP_Mod/files/11360533/DSM.0.3a.Ray.Receivers.x.784.Polar.with.Lens.Input.txt)
[DSM 0.3b Ray Receivers x 1109 [Mid] with [Lens Input].txt](https://github.com/starfi5h/DSP_Mod/files/11360534/DSM.0.3b.Ray.Receivers.x.1109.Mid.with.Lens.Input.txt)
[DSM 0.3c Ray Receivers x 1248 [Equator] with [Lens Input].txt](https://github.com/starfi5h/DSP_Mod/files/11360535/DSM.0.3c.Ray.Receivers.x.1248.Equator.with.Lens.Input.txt)

**Comment by Terrevil** [comment]
不止2个mod。

在锅星激活 focus local 之后问题消失。
ratio = 1 问题消失.

不是短期波动，是小时平均值。

**Comment by starfi5h** [comment]
那是否可以提供全部的mod列表, 以及存档?

**Comment by starfi5h** [comment]
我知道原因了。原因在于在原版更新透镜消耗的代码
bool useCata = time % 10L == 0L;
但是mod把工厂分散至不同tick后没有处理这个部分
导致有的星球过度消耗透镜, 有的星球没有消耗透镜

感谢回报, 我再想想要怎么做比较好

**Comment by Terrevil** [comment]
Selsion-DSPOptimizations
Semar-LongArm
Shad0wlife-AssemblerUI
soarqin-HideTips
soarqin-MechaDronesTweaks
soarqin-OrbitalCollectorBatchBuild
soarqin-UniverseGenTweaks
starfi5h-AutoMute
starfi5h-BulletTime
starfi5h-HoverTooltipDelay
starfi5h-MinerInfo
starfi5h-ModFixerOne
starfi5h-NebulaCompatibilityAssist
starfi5h-NoMilestone
starfi5h-ReorderTechQueue
starfi5h-SampleAndHoldSim
starfi5h-SphereEditorTools
testpushpleaseignore-Planet_Vein_Utilization
wingless-FreeCamera
xiaoye97-BiggerBuildRange
xiaoye97-LDBTool
Andy-SphereOpt
appuns-DSPAllPlanetInfo
appuns-DSPAutoSorter
appuns-DSPCompass
appuns-DSPNewGamePlus
appuns-DSPRecipeFinder
appuns-DSPStarMapMemo
appuns-DSPStationInfo
ardnaxelarak-DequeCraft
blacksnipebiu-Auxilaryfunction
blacksnipebiu-BetterUniverseInfo
blacksnipebiu-MoreStatInfo
blacksnipebiu-Multfuntion_mod
blacksnipebiu-StarMapTools
brokenmass-BuildCounter
ckcz123-TheyComeFromVoid
CommonAPI-CommonAPI
CommonAPI-DSPModSave
crecheng-CloseError
DanielHeEGG-SmartEjectors
dsp-mods-DspGameSpeed
Eirshy-ReBuffer
enriquein-MinerVeinCoverage
essium-FootballSphere
Fireball14-StationRangeLimiter
Fuhduki-BepInExConfig
Galactic_Scale-GalacticScale
GreyHak-DSP_Drone_Clearing
GreyHak-DSP_God_Mode_Button
GreyHak-DSP_Show_Grid
HarriXS-More_Replication
hetima-AutoReverse
hetima-BetterReform
hetima-LSTM
hetima-PlanetFinder
hetima-SnapBeltHeight
hetima-SplitterOverBelt
HiddenCirno-GenesisBook
IndexOutOfRange-DSPColorfulBuildGrid
IndexOutOfRange-DSPTransportStat
innominata-UltraNightLight
jinxOAO-MoreMegaStructure
jinxOAO-SmartTank
Klarkxy-IntelligentTransport
kremnev8-BlueprintTweaks
kumor-CustomCreateBirthStar
nebula-NebulaMultiplayerMod
nebula-NebulaMultiplayerModApi
PhantomGamers-IlLine
Powana-BetterGlobeMap
Raptor-BetterWarningIcons
Raptor-Blackbox
Raptor-ConstructionEnhancements
Raptor-DroneControl
Raptor-HideRandomTips
Raptor-UIEnhancements

**Comment by Terrevil** [comment]
Your code: 
0187d090-eecd-dd99-3695-871f3ba6ca0e 
has been copied to your clipboard. Just give it to a friend!
