### ISSUE TITLE
星球矿机速度不对

### ISSUE THREAD

**Issue by Terrevil** [starfi5h/DSP_Mod#20]
可能是科技+采矿速度没有正确应用。

使用你的mod后产出严重下滑。
问题复现条件
ratio=10
装时间加速3x 或 4x ：https://dsp.thunderstore.io/package/dsp-mods/DspGameSpeed/

**Comment by starfi5h** [comment]
如果你的星球矿机指的是这个mod
https://dsp.thunderstore.io/package/blacksnipebiu/PlanetMiner/
那么目前是还没有做兼容处理的
因为它更新星球矿机的逻辑是挂载在实验站的更新函式, 而不是物流站的更新函式
造成星球矿机被算在工厂内部, 没有每个tick都更新

**Comment by starfi5h** [comment]
已在0.5.4版本中加入兼容

**Comment by Terrevil** [comment]
![image](https://user-images.githubusercontent.com/132121086/236198081-6644a1dc-435d-41f7-a33a-838a37a49f1d.png)
![image](https://user-images.githubusercontent.com/132121086/236198239-49529829-ad93-41da-8191-6a4175189c41.png)
在ratio=10挂一个小时机结果对比。看铜，硅，钛数据
小时平均 产出 消耗比 应该 接近1:1
但原矿矿 产出消耗比  接近5:1
