### ISSUE TITLE
[SampleAndHoldSim] 0.5.5 當離開該星球時鍋的持續接收會被暫停

### ISSUE THREAD

**Issue by blacksnownight** [starfi5h/DSP_Mod#21]
理論上持續接收這個設定應該不受ratio影響(?)
先說設置吧，因產線規模有點大，所以有解鎖到使用ratio60
有點難解釋，就是以我個人的 額 射線傳輸效率1002級
即使是最外圍的行星，理論上也能到達100%接收(儘管會因接收不到射線而衰退，但起碼至少會是7到80% 不會只2到30%甚至於0%)
但當我離開行星時，它的持續接收就暫停了，然後以非常低的持續接收在工作，導致砸了一堆鍋，光子產量跟實際的鍋的數量對不太上
我記得在之前版本即使離開了行星，持續接收還是會自主工作到達100%
但現在是拍完鍋，上完透鏡，需要在該行星上等它暖鍋
還是錄個視屏比較好說明
https://youtu.be/Ifq2HLjIeoo
如視頻，即使在球內的行星，照理說是全天候100%接收的，但我離開且即使我ratio60 等個2分鐘，回去之後它只到10%(射線100%2分鐘總不會只跑1%吧) 在等待期間戴森球面板的請求功率也完全沒有增長

**Comment by starfi5h** [comment]
其實展示可以不用離開星球, 把Focus local關掉就可以了, 這樣你就能觀察到在非當地星球的慢速運作會是什麼樣子。

持續接收這個設定是受ratio影響的。
在[B站的視頻](https://www.bilibili.com/video/BV1oB4y1X78J/)有提到這個mod最好在產線穩定時使用。這是因為當你鋪完藍圖等待工廠熱機時, 傳送帶和鍋的持續接收都是屬於"內部", 因此當你離開星球後, 工廠的預熱時間就被依照ratio拉長, 以你的例子就是鍋要60倍的時間才能預熱完畢。

因此, 建議的做法是在改動完畢後在當地星球待到預熱完成再離開星球。

> 我記得在之前版本即使離開了行星，持續接收還是會自主工作到達100%

我印象中沒有，或可能是和其他mod交互作用了。如果有, 可以自行回退版本。

**Comment by blacksnownight** [comment]
我講不太出所以然，但覺得還是有問題
> 即使是最外圍的行星，理論上也能到達100%接收(儘管會因接收不到射線而衰退，但起碼至少會是7到80% 不會只2到30%甚至於0%)
似乎跟行星自轉有關係，就已說60倍的時間預熱
我因為擴了糖廠，所以反物質的需求有變的很大
所以我就到處去拍鍋，然後到個鳥拉不屎的地方掛機睡覺(10小時左右吧)
問題出在於最外圍的行星，當我睡醒後，確實有看到反物質的產量增加
但我在最外圍的行星拍的鍋持續接收卻是0%
比如說原始遊戲最外圍的鍋可以達到7~80%的持續接收
但當我放大到60倍所需時間時，它就像是完全接收不到射線

**Comment by blacksnownight** [comment]
沒事了，看著一個破鍋看了十來分鐘，漲到70多%又掉0%忽然注意到是橫躺自轉，南回歸線行不通。
