### ISSUE TITLE
请问bullet time mod 的'在背景执行自动保存'的功能是什么意思?,游戏不是自带主动保存吗?

### ISSUE THREAD

**Issue by newbienoobplayer** [starfi5h/DSP_Mod#24]
![image](https://github.com/starfi5h/DSP_Mod/assets/138718840/2ebe30df-9231-4b46-9193-503b86261e8a)

**Comment by starfi5h** [comment]
游戏的自动保存是在前台执行的, 因此在保存结束前游戏不会响应(画面静止且玩家无法进行任何操作)
BulletTime将保存的工作移至后台让玩家可以在保存的期间还可以进行部分的操作
https://www.bilibili.com/video/BV1wA4y1f7oN

**Comment by newbienoobplayer** [comment]
懂了,谢谢

**Comment by newbienoobplayer** [comment]
请问为什么视频里的逻辑帧率后面有显示游戏速度的百分比?

**Comment by starfi5h** [comment]
那是旧的版本

**Comment by newbienoobplayer** [comment]
谢谢
