### ISSUE TITLE
背景保存会报错

### ISSUE THREAD

**Issue by newbienoobplayer** [starfi5h/DSP_Mod#25]
![Screenshot (521)](https://github.com/starfi5h/DSP_Mod/assets/138718840/f23d9c17-9301-423b-9edf-249d9c2b2101)
大概三次了,辛苦大佬

**Comment by starfi5h** [comment]
https://steamcommunity.com/app/1366540/discussions/0/3106889614417840624
这是当存档文件在使用时, 被另一个程序更改的错误。通常是发生在OneDrive等云端同步的文件夹中。
[你可以试着把存档改到其他的位置。 ](https://www.bilibili.com/video/BV1ST4y1k7kL/?spm_id_from)

**Comment by newbienoobplayer** [comment]
懂了,谢谢

**Comment by newbienoobplayer** [comment]
嘿嘿 不好意思啊大佬能不能帮我看一下这个问题? 每一次都是刚进游戏放蓝图就报错
![Screenshot (542)](https://github.com/starfi5h/DSP_Mod/assets/138718840/e67c91cc-4ae2-43f4-9f88-7bb8253172ad)
![Screenshot (544)](https://github.com/starfi5h/DSP_Mod/assets/138718840/d71925cf-b1d5-4bad-9910-87e5f62e1fd6)
![Screenshot (545)](https://github.com/starfi5h/DSP_Mod/assets/138718840/a49c5fb4-19eb-4797-9ddc-b4c481a4e6e0)

**Comment by starfi5h** [comment]
我不处理仙术蓝图的问题, 建议去找蓝图制作者

**Comment by newbienoobplayer** [comment]
这不是仙术蓝图导致的 哪怕我放普通蓝图也会有这个问题

**Comment by newbienoobplayer** [comment]
而且我就是蓝图的制作者

**Comment by newbienoobplayer** [comment]
而且这个问题是最近才有的不关仙术蓝图的事
