### ISSUE TITLE
SampleAndHoldSim对Multfuntion mod的兼容性补丁失效

### ISSUE THREAD

**Issue by XGUI8011** [starfi5h/DSP_Mod#27]
![image](https://github.com/starfi5h/DSP_Mod/assets/106215893/d86a47cc-2f00-4b38-8956-662517c28b38)
模拟帧对Multfuntion mod的兼容性补丁失效
SampleAndHoldSim v0.5.7
Multfuntion v2.9.9

**Comment by starfi5h** [comment]
目前Multfuntion mod的代码正在频繁的大规模重构
等它稳定下来我再考虑修复兼容性补丁
在那之前请先用旧版或改用CheatEnabler

**Comment by starfi5h** [comment]
看起来他的逻辑又改变了
我不想继续追着做适配了
想要成就去装AchievementsEnabler跳检测吧
