### ISSUE TITLE
DeliverySlotsTweaks - Stack Size for items pinned before increase in `StackSize` or `StackMultiplier`. 

### ISSUE THREAD

**Issue by w-gates** [starfi5h/DSP_Mod#32]
DeliverySlotsTweaks - v1.3.1

For the `StackSize` and `StackMultiplier` option, there are two issues with items pinned before the mod is installed and one of those options is enabled.

1. For items that are pinned in your inventory (using the middle mouse button) only the original stack size is accepted.
2. Once combined, if you try to sort your inventory, the new items that were previously combined are separated into stacks of the original size. 

Edit: Issue only appears to happen for items I pinned to my inventory before installing the mod and enabling the `StackSize` and `StackMultiplier` option. Once I unpinned them it worked as expected, including after I re-pinned them. I have updated the issue title and information. I will leave this open for you to fix or just add the information to the readme as you wish.

**Comment by starfi5h** [comment]
I guess I can add a check when the game begins to adjust the pinned item slot to the desired stack size.
