### ISSUE TITLE
dark fog relay stations

### ISSUE THREAD

**Issue by andrewtranter** [starfi5h/DSP_Mod#35]
thankyou for updating the mod. however it breaks dark fog interaction.
so far I've noticed that it effects space fleets, and the dark fog space fleet.

with sample and hold enabled, my ships move very slowly in chunks. the chunks aren't equivalent to what they would have normally flown. eg, sample and hold sim of 2 they move less than half as fast.
for relay stations (the things attached to planet), when I destroy the anchor and place the foundation, the relay station moves away very slowly.

chunky, but same speed travel for ships, might be acceptable. however I suspect it might affect combat effectiveness.

**Comment by starfi5h** [comment]
Thanks for report.
I think I can make the hive in the local star system run in the normal speed to make the space units back normal. 
But I not sure what to do with the remote planets in the local star system then. The easy method is to also set them to normal speed, but then the performance gain will be reduced.

**Comment by andrewtranter** [comment]
seems mostly working, except for space hives don't even seem to spawn in when approached.
I turned it back down to 1x and it suddenly appears.

I forgot to test space combat above 1x sorry.

I can run at native fine when not launching many sails simultaneously, so I don't always use the mod. ill have to try to remember to test more.
