### ISSUE TITLE
[SampleAndHoldSim]新版本发现的三个黑雾相关问题

### ISSUE THREAD

**Issue by jessefjxm** [starfi5h/DSP_Mod#36]
1、高倍率下建筑扛不住攻击
现象：抽帧倍率提高到10后，原本能稳定运行12小时的刷怪阵地（保证修复速度大于被黑雾单元攻击的速度），5分钟后就出现建筑损失。
猜测：黑雾攻击帧被复制了多份，导致建筑被秒杀，来不及修复。
建议：考虑到黑雾单元攻击有间隔，或许可以限制攻击行为的复制。
![image](https://github.com/starfi5h/DSP_Mod/assets/1498592/0f64f93f-f645-4b32-a8f9-fa9dc32e356d)

2、黑雾能量供应出现严重不足
现象：黑雾地面基地、中继器皆出现了大面积的能量耗尽情况，导致刷怪量显著减少。
猜测：能量恢复帧被跳过了。
![image](https://github.com/starfi5h/DSP_Mod/assets/1498592/ff0d8611-7e5e-4460-8c23-d592e7fefd9d)

3、黑雾舰队卡在星球外围动弹不得
现象：如图，舰队在星球外不远处疯狂抖动，但就是不动
![image](https://github.com/starfi5h/DSP_Mod/assets/1498592/4d01e06d-4781-4495-9f75-5187b0370363)

**Comment by starfi5h** [comment]
感谢回报
如果方便的话, 是否可以提供存档让我测试?

**Comment by jessefjxm** [comment]
做了一些测试，把倍率从5倍调到1倍率后，过了10分钟，掉落统计上升了25%。

另外，1倍率下飞船卡位问题也消失了。

**Comment by jessefjxm** [comment]
我的存档：https://drive.google.com/file/d/1zc3wSytF2IktUMGNazho0WaoRfcOCHlg/view?usp=sharing
我在【蓝巨战斗星系】有两颗刷怪星球，各自在两极和赤道有刷怪区域。

**Comment by jessefjxm** [comment]
再次观察发现，只要有抽帧（2倍率）黑雾的船就会卡住，供能也会出现问题。关闭抽帧后，立刻供能跟上了。

**Comment by starfi5h** [comment]
新版本0.6.1推出了, 尝试修复黑雾逻辑

另外关于刷怪统计.. 我是没有对这一部分做倍增, 因为感觉这一个部分好像没有稳定的周期。所以现在显示的是真实的刷怪数量。
要倍增的统计应该为刷怪的战利品, 这是进到工厂内部的

**Comment by jessefjxm** [comment]
大佬牛逼，测试了一天，目前没发现什么问题。
挂机时遇到一个报错，看上去是跟黑雾巢穴有关：
![image](https://github.com/starfi5h/DSP_Mod/assets/1498592/e48edc0b-0924-4b1b-a43e-a417db79fd45)

**Comment by jessefjxm** [comment]
今天探索一颗新星球，在跟黑雾开打第一枪时遇到这个报错。由于昨天发现的bug，现在开的是1倍率。
![image](https://github.com/starfi5h/DSP_Mod/assets/1498592/c1d905e9-0cf5-4ad6-81d7-42bacfefb7e4)

**Comment by jessefjxm** [comment]
这两天学习到，黑雾地面基地的供能，几乎全部来自黑雾巢穴的定时货船补给。这个货船不会被玩家建筑拦截，每次能补充5GJ左右电量。如果这个货船无法正常供应，黑雾基地就会能量不足。

**Comment by starfi5h** [comment]
看来改整体黑雾太空巢穴的方案不太行, 因为星球每帧都在运动所以间隔更新的结果就是运动不正常...
我研究看看怎么只改枪骑的对地攻击频率或伤害好了

**Comment by jessefjxm** [comment]
今天发现黑雾舰队围攻的时候，可能出现百万大军瞬间齐聚，一轮齐射把我地面基地秒杀的情况，如图
![image](https://github.com/starfi5h/DSP_Mod/assets/1498592/5c187b54-f810-4d4a-980e-17e7c132d8e4)
正常情况下舰队会一艘艘送上来挨打，我的电浆炮阵列有充足时间一个个点名。但现在应该是瞬间上来太多，我基地护盾撑不住，就被秒杀了。

**Comment by starfi5h** [comment]
暂时先放弃干涉黑雾的逻辑了
在新版本v0.6.3版中止对枪骑的伤害做调整
血量的部分还在研究

**Comment by jessefjxm** [comment]
大佬，这两天发现一个可能跟MOD有关的问题，就是无法阻止中继器登陆。
1、仅在两极有电浆炮防空的情况下，半小时内就有多个星球成功登陆中继器。
当玩家在对应星球上时，则能有效防空。
2、两极有电浆炮防空+100%护盾覆盖的情况下，两小时内出现了一次成功登陆，如图。
最近几天官方增加了护盾禁止登录功能，按理说不可能还会登录的。
![image](https://github.com/starfi5h/DSP_Mod/assets/1498592/ba30963c-2151-40f4-ad07-9bb874301bf0)

**Comment by jessefjxm** [comment]
玩了一个月，感觉现在版本应该是没问题了。一颗有54个基地的星球，离开后性能占用明显下降，同时掉落物也正常，并且建筑物扣血也表现正常。
