### ISSUE TITLE
DeliverySlotsTweaks: Add option to add pickup items to logistics slot first instead of inventory

### ISSUE THREAD

**Issue by Pasukaru** [starfi5h/DSP_Mod#39]
Currently when picking up items, they don't get added into logistics slots. I'd prefer an option to insert them into logistics slots first, and only spill into inventory when logistic slot stack limit is reached.

Possibly also automatically add items from inventory into logistics slots whenever the inventory is sorted (Either via the sort button, or, if possible, when auto-sort happens from mods like DSPAutoSorter).

Both of these would help me a lot in reducing inventory clutter.

**Comment by starfi5h** [comment]
Config option `SortToDelieverySlots` has been added in 1.4.2

**Comment by Pasukaru** [comment]
Amazing, thanks!
