### ISSUE TITLE
Bottleneck模组与Blackbox模组共同使用时，打开统计UI会变得非常卡

### ISSUE THREAD

**Issue by jessefjxm** [starfi5h/DSP_Mod#41]
最近Blackbox模组有更新，但是测试发现，如果Bottleneck模组与Blackbox模组共同使用，那么在打开以下UI时，FPS会立刻降低到14~20：
· 生产统计
· 电力统计
· 研究统计
· 戴森球
即使Blackbox模组是初始化状态，没有跟踪任何生产线，也是如此。
不确定是哪边的兼容性问题。但是因为这两个模组都非常强大，舍不得删，不知道大佬能找到问题吗？

**Comment by starfi5h** [comment]
我只用这两个mod在你之前给我的存档测试无法复现, 没有观察到FPS降低
这个问题在新开存档中也有吗?

**Comment by jessefjxm** [comment]
奇怪，我重新装了一遍mod后，就无法复现了……
刚才用一个新配置，一开始只装bottleneck和blackbox，后面把所有mod都装了回来，都没卡

**Comment by jessefjxm** [comment]
又研究了半天，感觉只是单纯的“BottleNeck在统计全星区”模式下会明显变卡，跟blackbox没关系……
