### ISSUE TITLE
DeliverySlotsTweaks more ColCount?

### ISSUE THREAD

**Issue by alpe12** [starfi5h/DSP_Mod#42]
Would it be possible to increase the limit of 5? To maybe 6 or 7.
Thanks anyway.

**Comment by alpe12** [comment]
Okay. 😢 
Hope they change it.
Thanks.

**Comment by alpe12** [comment]
@starfi5h Would it already be possible to add one more?
Maybe they changed something in the code that would allow it in these years.
Thanks anyway.

**Comment by starfi5h** [comment]
No.
