### ISSUE TITLE
Ability to disable Relay protection when shield is deployed

### ISSUE THREAD

**Issue by c0ldfusi0n** [starfi5h/DSP_Mod#46]
Could this be made an option in the config file please? Thank you

**Comment by starfi5h** [comment]
Why? This is to fix the bug that some relay will land on a planet even when there is full shield.
https://github.com/starfi5h/DSP_Mod/issues/36#issuecomment-1879502153
If you want relay to land on the target planet, don't place shields on that planet, or go to that star system. The protection does not work on the local system where the player is located.

**Comment by c0ldfusi0n** [comment]
I didn't know this was a bug fix. I have a farm set up on a planet currently with only one relay/base, and want more relays to populate the unprotected areas so I can kill more dark fog and get more items. Since this farm is protected from space attacks by one sheild, no more relays are landing, this is why I wanted to be able to disable this function.
Can I ask if this mod makes the game believe the entire planet is protected by a planetary sheild and means that everything on it is protected from space laser attacks?

**Comment by starfi5h** [comment]
I recommend just use Multfuntion mod to create DF bases and make building invincible for your requirements.

**Comment by c0ldfusi0n** [comment]
It's ok, I will go back to using v0.6.3 where the relay code isn't present and hope that you will remove the code for the relay in a future version once the bug is patched by the Devs. Thanks
