### ISSUE TITLE
DSP Patch V0.10.29.28154 breaks DeliverySlotsTweaks due to changes to logistics slot counts

### ISSUE THREAD

**Issue by herrchin** [starfi5h/DSP_Mod#47]
Added upgrade level 7 for "Inventory Capacity," providing an additional 2 columns of item inventory slots and 1 column of logistics list slots for Icarus.

**Comment by JoeMShanahan** [comment]
I also get an error when loading the game relating to (I think) the new sorter.

**Comment by herrchin** [comment]
DeliverySlotsTweaks 1.5.1 just released appears to resolve the incompatibility.
