### ISSUE TITLE
DeliverySlotsTweaks

### ISSUE THREAD

**Issue by ChinaShopBully** [starfi5h/DSP_Mod#49]
Hey starfi5h, I'm not sure if this is actually a DeliverySlotsTweaks problem, or AutoSorter, but there's something strange going on with BABs and signal towers. Check out this thread: https://old.reddit.com/r/Dyson_Sphere_Program/comments/1ah6kjy/serious_issue_with_bab_repairs_after_patch_max/koouors/

I wonder if somehow the code that is adjusting item movement within the player's inventory is also doing it with the BAB inventory, causing those items to be unavailable for use in rebuilding...

Not sure if this is something you can fix, but I wanted to mention it. 

Thanks for all the great mods!

**Comment by matthock** [comment]
Will second this one. I am also running in to issues where I have the items in inventory but they won't populate ghosts since the February game updates while running DST.

**Comment by matthock** [comment]
It seems to have fixed the problem I was encountering, I loaded my save and the big blueprint I'd just placed that was only half populated immediately populated the rest of the way and finished building. Thank you for the prompt fix!
