### ISSUE TITLE
exception after remove a Planetary Logistics Station

### ISSUE THREAD

**Issue by yudenzel** [starfi5h/DSP_Mod#5]
Steps to reproduce:
1. place a PLS
1. remove that PLS

![image](https://user-images.githubusercontent.com/4387218/164768208-2b7018ea-5940-4fee-b48f-866f5a0a748a.png)

**Comment by starfi5h** [comment]
fix in v0.2.0 69df1d723ed63fd013238fd0d8f893498818270a
