### ISSUE TITLE
[ErrorAnalyzer]更新后遇到无法使用CloseError关闭错误框的现象，希望能内置可关闭错误框功能

### ISSUE THREAD

**Issue by jessefjxm** [starfi5h/DSP_Mod#52]
CloseError这个模组能关闭右上角错误框，主要作用是：
1、遇到报错时，可以实现手动存档——手动读档——关闭错误框的操作，减少一次无畏的自动存档尝试。这是因为在出现报错的情况下，退回主菜单时游戏依然会强制存档，对于大后期档来说会浪费好几分钟时间。
2、部分只出现一次的错误可以直接关闭，免得碍眼。
最近ErrorAnalyzer更新后，注意到有些情况下（暂未确定复现条件）错误框不会在右上角渲染CloseError添加的[x]按钮，因而无法关闭。
由于CloseError很久没更新了，希望ErrorAnalyzer能集成这个便利性功能。

**Comment by starfi5h** [comment]
ErrorAnalyzer提供的[Copy]复制按钮不是也可以关闭吗?

**Comment by jessefjxm** [comment]
原来如此，之前都没有注意到……
