### ISSUE TITLE
DeliverySlotTweaks: Items in logistics slots don't seem to count when examining the requirements for crafting items

### ISSUE THREAD

**Issue by ChinaShopBully** [starfi5h/DSP_Mod#53]
In this case, I am trying to craft a Tier 2 Assembler, and I have plenty of Tier 1 assemblers in my logistics slots, but for the purposes of the crafting system, it thinks I have none available, I'm assuming becuase the crafting algorithm only looks in the normal inventory. It will still build when I craft. 

![image](https://github.com/starfi5h/DSP_Mod/assets/110853795/cfe141d1-8b66-4b0a-811c-d7e7d11f0933)

**Comment by starfi5h** [comment]
My local test is normal.
![image](https://github.com/starfi5h/DSP_Mod/assets/50672801/3b5bc49b-834d-43c5-9dd5-600614295b54)

Seems like mods conflict. What other mods do you use?
