### ISSUE TITLE
DeliverySlotsTweaks - Fuel is not replenished

### ISSUE THREAD

**Issue by SunSerega** [starfi5h/DSP_Mod#55]
[LogOutput.log](https://github.com/starfi5h/DSP_Mod/files/14574840/LogOutput.log)

The related setting is on:
[starfi5h.plugin.DeliverySlotsTweaks.txt](https://github.com/starfi5h/DSP_Mod/files/14574849/starfi5h.plugin.DeliverySlotsTweaks.txt)
(renamed to .txt so GitHub would accept it)

The fuel is auto-sorted to the logistics but is neither taken from there automatically when the fuel rod is spent nor when Ctrl+clicking inventory with `Mecha Panel` (`C` by default) open.

In case it matters, the only fuel I have in inventory and logistic slots is `Antimatter Fuel Rod`.

**Comment by SunSerega** [comment]
Crafting from those slots also doesn't work... I guess the `DeliveryPackagePatch.TakeItem_Transpiler` is somehow outdated in `v0.10.29.21950`?

**Comment by SunSerega** [comment]
Idk if I should open a separate issue, it all seems related... But when you fix this, can you please also enable warper refill the same way?

**Comment by starfi5h** [comment]
It's not recommended to use BepInEx version higher than 5.4.17 as it sometimes will break the transpilers.

**Comment by SunSerega** [comment]
Ah, I see. And it's only replenished when the stack is fully spent. Well, I'd prefer the stockpile to always stay full, but this is fine too.

But what about warpers? Should I open a separate issue as a feature request to also refill those?

**Comment by starfi5h** [comment]
Add in v1.5.4

**Comment by SunSerega** [comment]
It seems to only take out a single warper, instead of a stack. I'm alright with that, but is it intended?

**Comment by starfi5h** [comment]
It is intended.
