### ISSUE TITLE
[PlanetwideSpray] Product spraying three-level production increase agent？

### ISSUE THREAD

**Issue by yegetables** [starfi5h/DSP_Mod#58]
Can the product be sprayed with a third-level production enhancer before being stored in the warehouse to facilitate use and transportation?

For example, now it is: fuel rods without spraying the production enhancer
![image](https://github.com/starfi5h/DSP_Mod/assets/37119488/7787ddee-33e5-493c-96a0-b605e6d05e94)

Expected results: Fuel rods sprayed with production enhancer
![image](https://github.com/starfi5h/DSP_Mod/assets/37119488/d458fc8a-79a9-4d68-99db-2afcd7358709)

There are other situations, such as: mined iron ore and copper ore, production foundation (the foundation sprayed with production increase agent can reduce sand consumption)
![image](https://github.com/starfi5h/DSP_Mod/assets/37119488/4e846d0f-f672-4139-939e-4164a50dbf51)
![image](https://github.com/starfi5h/DSP_Mod/assets/37119488/c5c54c96-c6b8-4d0c-bf06-5182ebe69cbf)

**Comment by starfi5h** [comment]
I've push an update v1.0.1.
you can now set `Spray All Cargo = true` in the config file to spray all item grab by sorters, including the product.
