### ISSUE TITLE
[PlanetWideSpray] Pile Sorters don't spray out of Assemblers.

### ISSUE THREAD

**Issue by Teck1015** [starfi5h/DSP_Mod#59]
Force Proliferator Level config doesn't seem to work with Pile Sorters.

Upgrading to Pile sorters and pulling out of Assembler doesn't spray items. Downgrading back to Mk III sorter spray items.

**Comment by starfi5h** [comment]
I can't reproduce this issue.
Make sure to set `Spray All Cargo` = true if you want to spray the output.

**Comment by edvat** [comment]
hey I'm having the same issue and I have Spray All Cargo set to true but the pile sorters don't spray anything while the Mk III does

**Comment by starfi5h** [comment]
@edvat List all the mods and the screenshot of pile sorters building layout.

**Comment by edvat** [comment]
oh sorry I was thinking they'd spray output not input. it does work as intended.
