### ISSUE TITLE
LogisticsBotsTweaks

### ISSUE THREAD

**Issue by AzuralCraft** [starfi5h/DSP_Mod#63]
感觉可以增加一个提升装载量和每秒放飞数量（类似LocalTransportFix）的选项，

**Comment by starfi5h** [comment]
修改装载量可以做
物流配送器游戏在原版中是每3个游戏刻后检查一次, 也就是20/sec
用mod改的话上限是每1个游戏刻后检查一次, 60/sec
这样也只有3倍, 感觉效益不大
