### ISSUE TITLE
1.2.8 breaks multiplayer?

### ISSUE THREAD

**Issue by Tuumke** [starfi5h/DSP_Mod#9]
Latest version (1.2.8?) breaks Multiplayer.

```ini
An error has occurred! Game version 0.9.27.14546
Mods used: [IlLine1.0.0] [LDBTool2.0.6] [DSP Mod Save1.1.4] [DSP Common API1.5.4.0] [NebulaMultiplayerMod0.8.10.2] [NebulaMultiplayerModApi1.3.0.7] [BulletTime1.2.8] [Common API Nebula Compatibility1.5.4.0] 
[Nebula Error] Nebula Multiplayer Mod is incompatible
Unhandled exception occurred while patching the game.
```

**Comment by Tuumke** [comment]
Also made an issue on Nebula Multiplayer:
https://github.com/hubastard/nebula/issues/580

**Comment by starfi5h** [comment]
It's the game 0.9.27 that breaks Nebula Multiplayer 0.8.10.
In case someone still wants to play in the old version, I make BulletTime v1.2.9 compatible with game 0.9.26.
